defaults: &defaults
  allow_dynamic_fields: false
  identity_map_enabled: true

development:
  <<: *defaults
  host: localhost
  database: pickingwords_development

test:
  <<: *defaults
  host: localhost
  database: pickingwords_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
