defaults: &defaults
  allow_dynamic_fields: false
  identity_map_enabled: true

development:
  <<: *defaults
  host: localhost
  database: pickingwords_development

test:
  <<: *defaults
  host: localhost
  database: pickingwords_test

production:
  <<: *defaults
  uri: <%= ENV['MONGOLAB_URI'] %>
